# Generated by Django 6.0.6 on 2026-06-19 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0004_remove_otp_add_finalizing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapplication',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientapplication',
            name='retry_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientapplication',
            name='phone_number',
            field=models.CharField(help_text='Primary phone linked to Irembo profile', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits and start with 07 followed by 8 digits.', regex='^07[2389]\\d{7}$')]),
        ),
    ]
