# Generated by Django 6.0.6 on 2026-06-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0005_clientapplication_last_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapplication',
            name='log_output',
            field=models.TextField(blank=True, help_text='Detailed execution logs for the application task', null=True),
        ),
    ]
