# Generated by Django 6.0.6 on 2026-06-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0007_clientapplication_user_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapplication',
            name='failure_reason',
            field=models.CharField(blank=True, help_text='Stored Kinyarwanda reason code for automation failure', max_length=255, null=True),
        ),
    ]
