# Generated by Django 6.0.6 on 2026-06-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0008_clientapplication_failure_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapplication',
            name='comment',
            field=models.TextField(blank=True, help_text='User comments about this application', null=True),
        ),
    ]
