# Generated by Django 6.0.6 on 2026-06-27 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0009_clientapplication_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRunHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('payment_status', models.CharField(max_length=20)),
                ('billing_number', models.CharField(blank=True, max_length=50, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('log_output', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_history', to='automation_app.clientapplication')),
            ],
            options={
                'verbose_name': 'Application Run History',
                'verbose_name_plural': 'Application Run Histories',
                'ordering': ['-run_date'],
            },
        ),
    ]
